version: "3.8"

services:
  app:
    image: azfarsuhail/real-time-messaging-app:latest
    container_name: real-time-messaging-app
    restart: always
    networks:
      - messaging-network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "start"]